name: Terraform Docs Pipeline
run-name: "🚀 Executado por ${{ github.actor }} - Mensagem: ${{ github.event.head_commit.message }}"
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    name: Gerar Documentação (terraform-docs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para evitar erros ao fazer push

      - name: Configurar o Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform
        run: terraform init

      - name: Rodar Terraform Docs via Docker
        run: |
          docker run --rm \
            --volume "$(pwd):/workspace" \
            quay.io/terraform-docs/terraform-docs:latest \
            markdown table --output-file README.TF.md --output-mode inject /workspace

      - name: Verificar se há mudanças
        run: |
          if [[ -n "$(git status --porcelain README.TF.md)" ]]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit e Push do README.TF.md atualizado
        if: env.CHANGES_DETECTED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.TF.md
          git commit -m "Atualiza documentação Terraform via GitHub Actions"
          git push origin HEAD:${{ github.ref_name }}
